### ISSUE TITLE
Error: <convertible.rb:7:in `do_layout': undefined method `converter'>

### ISSUE THREAD

**Issue by fcalderan** [rustygeldmacher/jekyll-contentblocks#4]
I'm using jekyll-contentblocks (0.0.2) with jekyll (2.3.0) and ruby 2.1.1

In one template `code.html`I've defined this block

```
{% contentfor prismcode %}
   <pre><code>...</code></pre>
{% endcontentfor %}
```

and inside the layout I've included this block with

```
    {% capture result %}{% contentblock prismcode %}{% endcapture %}
    {% if result != '' %}
       <script src="..."></script>    
    {% endif %}  
```

When I compile I get this error

```
Configuration file: _config.yml
Configuration file: _config_dev.yml
            Source: ./src
       Destination: ./dev
      Generating... 

/Users/[... full path ...]/gems/jekyll-contentblocks-0.0.2/lib/jekyll-contentblocks/convertible.rb:7:in `do_layout': undefined method `converter' for #<Jekyll:Page @name="code.html"> (NoMethodError)
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/page.rb:122:in `render'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/site.rb:263:in `block in render'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/site.rb:262:in `each'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/site.rb:262:in `render'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/site.rb:45:in `process'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/command.rb:28:in `process_site'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/commands/build.rb:55:in `build'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/commands/build.rb:33:in `process'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/gems/jekyll-2.3.0/bin/jekyll:18:in `<top (required)>'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/bin/jekyll:23:in `load'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/bin/jekyll:23:in `<main>'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/bin/ruby_executable_hooks:15:in `eval'
    from /Users/fcalderan/.rvm/gems/ruby-2.1.1@primertstatic/bin/ruby_executable_hooks:15:in `<main>'
```

Thank you
Fabrizio

**Comment by mshick** [comment]
I'm having this problem now. Running both system ruby (2.0.0) on 10.11, and using rbenv with latest everything. I used the bundler install approach, I'm working in a totally vanilla jekyll project, and have these versions: ruby (2.2.3p173), jekyll (2.5.3) , jekyll-contentblocks (1.0.0), gem (2.4.8).

All steps to reproduce:

```sh
gem install jekyll
jekyll new my-site
cd my-site
bundle init
echo 'gem "jekyll-contentblocks"' >> Gemfile
bundle install
# create _plugins/bundler.rb
jekyll build
# -> jekyll 2.5.3 | Error:  undefined method `do_layout' for module `Jekyll::Convertible'
```

**Comment by rustygeldmacher** [comment]
Yikes, I will check this out. For now I'd pin JCB to a pre-1.0 version.

**Comment by mshick** [comment]
Thanks, that seems to be working.

**Comment by rustygeldmacher** [comment]
Hopefully that will be a temporary workaround though -- thanks for the steps to reproduce, I'm working on fix right now.

**Comment by rustygeldmacher** [comment]
@mshick -- I just release v1.0.1 of jekyll-contentblocks that should address this problem. Please give it a try and let me know how it goes.

Also, one tip: do `bundle exec jekyll build` to build the site -- this will make it so you don't get warnings about json (they're unrelated to jekyll-conentblocks, but I got those warnings w/ Ruby 2.1.1)

**Comment by mshick** [comment]
latest version is working great for me. thanks again!
